/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CateringEventsRouteImport } from './routes/catering-events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DiningExperienceRouteImport } from './routes/dining-experience'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ReservationsRouteImport } from './routes/reservations'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MenuIndexRouteImport } from './routes/menu.index'
import { Route as MenuDishIdRouteImport } from './routes/menu_.$dishId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CateringEventsRoute = CateringEventsRouteImport.update({
  id: '/catering-events',
  path: '/catering-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DiningExperienceRoute = DiningExperienceRouteImport.update({
  id: '/dining-experience',
  path: '/dining-experience',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationsRoute = ReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuIndexRoute = MenuIndexRouteImport.update({
  id: '/menu/',
  path: '/menu/',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuDishIdRoute = MenuDishIdRouteImport.update({
  id: '/menu_/$dishId',
  path: '/menu/$dishId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/catering-events': typeof CateringEventsRoute
  '/contact': typeof ContactRoute
  '/dining-experience': typeof DiningExperienceRoute
  '/feedback': typeof FeedbackRoute
  '/gallery': typeof GalleryRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reservations': typeof ReservationsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/menu/$dishId': typeof MenuDishIdRoute
  '/menu/': typeof MenuIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/catering-events': typeof CateringEventsRoute
  '/contact': typeof ContactRoute
  '/dining-experience': typeof DiningExperienceRoute
  '/feedback': typeof FeedbackRoute
  '/gallery': typeof GalleryRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reservations': typeof ReservationsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/menu/$dishId': typeof MenuDishIdRoute
  '/menu': typeof MenuIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/catering-events': typeof CateringEventsRoute
  '/contact': typeof ContactRoute
  '/dining-experience': typeof DiningExperienceRoute
  '/feedback': typeof FeedbackRoute
  '/gallery': typeof GalleryRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reservations': typeof ReservationsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/menu_/$dishId': typeof MenuDishIdRoute
  '/menu/': typeof MenuIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/catering-events'
    | '/contact'
    | '/dining-experience'
    | '/feedback'
    | '/gallery'
    | '/privacy-policy'
    | '/reservations'
    | '/sitemap.xml'
    | '/menu/$dishId'
    | '/menu/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/catering-events'
    | '/contact'
    | '/dining-experience'
    | '/feedback'
    | '/gallery'
    | '/privacy-policy'
    | '/reservations'
    | '/sitemap.xml'
    | '/menu/$dishId'
    | '/menu'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/catering-events'
    | '/contact'
    | '/dining-experience'
    | '/feedback'
    | '/gallery'
    | '/privacy-policy'
    | '/reservations'
    | '/sitemap.xml'
    | '/menu_/$dishId'
    | '/menu/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CateringEventsRoute: typeof CateringEventsRoute
  ContactRoute: typeof ContactRoute
  DiningExperienceRoute: typeof DiningExperienceRoute
  FeedbackRoute: typeof FeedbackRoute
  GalleryRoute: typeof GalleryRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ReservationsRoute: typeof ReservationsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  MenuDishIdRoute: typeof MenuDishIdRoute
  MenuIndexRoute: typeof MenuIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catering-events': {
      id: '/catering-events'
      path: '/catering-events'
      fullPath: '/catering-events'
      preLoaderRoute: typeof CateringEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dining-experience': {
      id: '/dining-experience'
      path: '/dining-experience'
      fullPath: '/dining-experience'
      preLoaderRoute: typeof DiningExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservations': {
      id: '/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof ReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/': {
      id: '/menu/'
      path: '/menu'
      fullPath: '/menu/'
      preLoaderRoute: typeof MenuIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu_/$dishId': {
      id: '/menu_/$dishId'
      path: '/menu/$dishId'
      fullPath: '/menu/$dishId'
      preLoaderRoute: typeof MenuDishIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CateringEventsRoute: CateringEventsRoute,
  ContactRoute: ContactRoute,
  DiningExperienceRoute: DiningExperienceRoute,
  FeedbackRoute: FeedbackRoute,
  GalleryRoute: GalleryRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ReservationsRoute: ReservationsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  MenuDishIdRoute: MenuDishIdRoute,
  MenuIndexRoute: MenuIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
